### ISSUE TITLE
OSError: [Errno 122] Disk quota exceeded

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [GeoscienceAustralia/dea-notebooks#755]
While running the notebook on NCI and save data to a folder on /home/586/tn9356, I encounter this problem. 
OSError: [Errno 122] Disk quota exceeded: '/home/586/tn9356/.local/share/jupyter/runtime/kernel-b6f86981-8cd2-493e-958b-8b4847dcde9a.json'

What my script does is going through a list of points, load data, and save them as .nc files. The data were not stored in the memory.

The whole error message is below:

[I 11:04:00.916 LabApp] Build is up to date
Generating grammar tables from /g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/586/tn9356/.cache/black/19.10b0/Grammar3.6.10.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/586/tn9356/.cache/black/19.10b0/tmpkdw6jnzq'
Generating grammar tables from /g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/586/tn9356/.cache/black/19.10b0/PatternGrammar3.6.10.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/586/tn9356/.cache/black/19.10b0/tmpmazqp_ko'
|LabApp - ERROR - Uncaught exception GET /api/contents/dea-notebooks/Dieback/download_S2_data.ipynb?type=notebook&content=1&1612915443928 (::1)
HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/contents/dea-notebooks/Dieback/download_S2_data.ipynb?type=notebook&content=1&1612915443928', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get
    path=path, type=type, format=format, content=content,
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 429, in get
    model = self._notebook_model(path, content=content)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 388, in _notebook_model
    self.mark_trusted_cells(nb, path)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 508, in mark_trusted_cells
    trusted = self.notary.check_signature(nb)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/nbformat/sign.py", line 439, in check_signature
    return self.store.check_signature(signature, self.algorithm)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/nbformat/sign.py", line 239, in check_signature
    (datetime.utcnow(), algorithm, digest),
sqlite3.OperationalError: database is locked
[W 11:04:10.090 LabApp] Unhandled error
-[W 11:04:10.278 LabApp] Notebook dea-notebooks/Dieback/UQ_Visual.ipynb is not trusted
\LabApp - ERROR - Uncaught exception POST /api/sessions?1612915452255 (::1)
HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri='/api/sessions?1612915452255', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/manager.py", line 304, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/manager.py", line 251, in pre_start_kernel
    self.write_connection_file()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/connect.py", line 474, in write_connection_file
    kernel_name=self.kernel_name
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_core/paths.py", line 437, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
OSError: [Errno 122] Disk quota exceeded: '/home/586/tn9356/.local/share/jupyter/runtime/kernel-c3814fd6-8b16-4a62-be83-50183e5d76d9.json'
[W 11:04:12.398 LabApp] Unhandled error
LabApp - ERROR - Uncaught exception POST /api/sessions?1612915495160 (::1)    -
HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri='/api/sessions?1612915495160', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/manager.py", line 304, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/manager.py", line 251, in pre_start_kernel
    self.write_connection_file()
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/connect.py", line 474, in write_connection_file
    kernel_name=self.kernel_name
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_client/connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/jupyter_core/paths.py", line 437, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
OSError: [Errno 122] Disk quota exceeded: '/home/586/tn9356/.local/share/jupyter/runtime/kernel-b6f86981-8cd2-493e-958b-8b4847dcde9a.json'
[W 11:04:55.194 LabApp] Unhandled error
^C[I 11:20:46.413 LabApp] interrupted

**Comment by robbibt** [comment]
Hey @Daniel-Trung-Nguyen! This can happen when you save files directory to your home directory on the VDI. It only has about 2 gb of storage, and once that runs out you'll get errors like this. Usually, we only use the home directory for demos, and clone `dea-notebooks` to another location on the NCI's `gdata` disk if it's for a more serious analysis. The problem is that `gdata` requires you to be a member of a specific NCI project to have access to the drive.

The best thing might be to email dea@ga.gov.au with more info about your project, and we can see if there's anything else we can do from there.

**Comment by Daniel-Trung-Nguyen** [comment]
Hi @robbibt, thanks for the prompt response! I am a member of different projects such as rs0, xu18, if87, fk4, fj7. However, I am not sure if I can write data to these folders on the /gdata disk and if my data will be permanent. From the "How to use VDI" guide (https://opus.nci.org.au/display/Help/2.+How+to+use+VDI), it states that I can store data to /local or /short. However, when I tried to do so, it said "[Errno 13] Permission denied:". Do I need to ask for specific permission somewhere to temporarily store data there?
Appreciate your help!
Cheers,
Daniel

**Comment by Daniel-Trung-Nguyen** [comment]
I got the answer. Using /local/if87 works. Thanks!
